#### TASK :
1. CREATE ARRAYS WITHS ALL THE DATATYPES AVAIALBLE N NUMPY

In [2]:
import numpy as np

In [2]:
#integer
arr = np.array([1,2,3,4,5], dtype = 'i')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [6]:
#boolean
arr = np.array([0,1,2,3,4,5], dtype = 'bool_')
print(arr)
print(arr.dtype)

[False  True  True  True  True  True]
bool


In [9]:
#unsigned integer
arr = np.array([5,6,7,8,9], dtype='uint16')
print(arr)
print(arr.dtype)

[5 6 7 8 9]
uint16


In [10]:
#float
arr = np.array([1.2, 3.4, 5.6, 7.8, 9.1], dtype = 'f')
print(arr)
print(arr.dtype)

[1.2 3.4 5.6 7.8 9.1]
float32


In [11]:
#complexfloat
arr = np.array([2+6j, 7.2+3j, 6+7.6j, 1+8.3j], dtype = 'complex_')
print(arr)
print(arr.dtype)

[2. +6.j  7.2+3.j  6. +7.6j 1. +8.3j]
complex128


In [13]:
#timedelta
arr = np.timedelta64(6, 'Y')
print(arr)
print(arr.dtype)

6 years
timedelta64[Y]


In [14]:
#datetime
arr = np.array(['2001-01-01T12:00', '2002-02-03T13:56:03.172'], dtype = 'M')
print(arr)
print(arr.dtype)

['2001-01-01T12:00:00.000' '2002-02-03T13:56:03.172']
datetime64[ms]


In [15]:
#object
arr = np.array([1,5,7,8,9], dtype='O')
print(arr)
print(arr.dtype)

[1 5 7 8 9]
object


In [16]:
#string
arr = np.array(['Hello', 'Everyone', 'Good', 'Morning'], dtype = 'S')
print(arr)
print(arr.dtype)

[b'Hello' b'Everyone' b'Good' b'Morning']
|S8


In [17]:
#unicode string
arr = np.array([u'\u03bcm', u'\u2202r', u'\u2206\u03bb'], dtype='U')
print(arr)
print(arr.dtype)

['μm' '∂r' '∆λ']
<U2


In [5]:
#void
import numpy as np
arr = np.void([])
print(arr)
print(arr.dtype)

[]
|V8
